<<<<<<< HEAD
﻿"use client"

import { useState, useEffect } from "react"
import MenuLateral from "../components/MenuLateral"
import Topo from "../components/Topo"
import Protecao from "../components/Protecao"
import { usePathname } from "next/navigation"
import "./globals.css"

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [menuAberto, setMenuAberto] = useState(true)
  const pathname = usePathname()
  const isLoginPage = pathname === "/login"

  useEffect(() => {
    const checkMobile = () => {
      if (window.innerWidth < 768) setMenuAberto(false)
    }
    checkMobile()
    window.addEventListener("resize", checkMobile)
    return () => window.removeEventListener("resize", checkMobile)
  }, [])

  const toggleMenu = () => setMenuAberto(!menuAberto)

  return (
    <html lang="pt-BR">
      <body className="bg-gray-100">
        {isLoginPage ? (
          <>{children}</>
        ) : (
          <Protecao>
            <Topo toggleMenu={toggleMenu} />
            <MenuLateral aberto={menuAberto} />
            <main className={`transition-all duration-300 pt-16 ${menuAberto ? "ml-64" : "ml-20"}`}>
              <div className="p-6">{children}</div>
            </main>
          </Protecao>
        )}
      </body>
    </html>
  )
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
>>>>>>> 0334d32a57f57a93a948693c4319ace0b2a7fbce
}
